FROM almalinux:9
ARG Name="pavan"\
    wife="puja"\
    age="26"\
    profession="software"
ENV Name="puja"\
    age="27"\
    own=$wife
RUN echo "Name:$Name, wife:$wife, age:$age, own:$own "
CMD ["sleep","500"]

